export const dataDB = [
    {
        id: 1,
        name: "Blusa 1",
        urlImages: "./assets/blusa1.jpg",
        stock: 5,
        price: 1000,
    },
    {
        id: 2,
        name: "Blusa 2",
        urlImages: "./assets/blusa2.png",
        stock: 6,
        price: 2000,
    },
    {
        id: 3,
        name: "Blusa 3",
        urlImages: "./assets/blusa3.png",
        stock: 7,
        price: 3000,
    },
    {
        id: 4,
        name: "Blusa 4",
        urlImages: "./assets/blusa4.jpg",
        stock: 8,
        price: 4000,
    },
    {
        id: 5,
        name: "Pantalon 1",
        urlImages: "./assets/pantalones2.png",
        stock: 9,
        price: 5000,
    },
    {
        id: 6,
        name: "Pantalon 2",
        urlImages: "./assets/pantalones3.png",
        stock: 10,
        price: 6000,
    },
    {
        id: 7,
        name: "Vestido 1",
        urlImages: "./assets/vestido1.jpg",
        stock: 11,
        price: 7000,
    },
    {
        id: 8,
        name: "Vestido 2",
        urlImages: "./assets/vestido2.png",
        stock: 12,
        price: 8000,
    },
    {
        id: 9,
        name: "Vestido 3",
        urlImages: "./assets/vestido3.png",
        stock: 13,
        price: 9000,
    },
];
